### ISSUE TITLE
Sequelize Not Defined in items.js (line 5)

### ISSUE THREAD

**Issue by dpkillian** [DSEapps/upkeep#15]
Full error:

```
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:237:13
/Users/dkillian/unc/projects/project2/upkeep/models/items.js:5
    item_id:        { type: Sequelize.INTEGER, primaryKey: true },
                            ^

ReferenceError: Sequelize is not defined
    at module.exports (/Users/dkillian/unc/projects/project2/upkeep/models/items.js:5:29)
```
Not sure why Sequelize definition isn't picked up in index.js.

**Comment by esharri2** [comment]
@dpkillian Sequelize is not defined in that file, and I don't think it needs to be. You are passing DataTypes into that function, which is the object you need. Just replace with `Sequelize` with `DataTypes`.  (I believe this is how that blog app was done ... you could double check in there to confirm.

**Comment by dpkillian** [comment]
OK.  I'll try it.  Thanks!!

**Comment by dpkillian** [comment]
Well, that definitely helped.  But there is now another, larger problem.

```
[nodemon] starting `node server.js`
sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:237:13
Unhandled rejection Error: Cyclic dependency found. items is dependent of itself.
Dependency chain: items -> tasks => items
    at visit (/Users/dkillian/unc/projects/project2/upkeep/node_modules/toposort-class/build/toposort.js:173:27)
    at visit (/Users/dkillian/unc/projects/project2/upkeep/node_modules/toposort-class/build/toposort.js:212:29)
```
This is a result of me not understanding how to properly setup Sequelize for associations.  Ugh.  I have it figured out in MySQL.

**Comment by dpkillian** [comment]
I've tried reading online docs and have altered the belongsTo and hasMany statements a few different ways.  I keep getting the "cyclic dependency"  error.

**Comment by dpkillian** [comment]
I'll check in what I have...

**Comment by esharri2** [comment]
Ew, this is a tough one. I would nominate these associations to be removed, but not sure...

```
 Items.hasMany(models.users, {
      // onDelete: "cascade"
    });

   Tasks.hasMany(models.items, {
      // onDelete: "cascade"
    });

    Tasks.hasMany(models.users, {
      // onDelete: "cascade"
    });
```

**Comment by dpkillian** [comment]
![table-associations](https://user-images.githubusercontent.com/22895967/35302046-388d8ccc-005b-11e8-8a1a-7f0bfc8bb98d.JPG)
I think I need to ask Jack about these tables.  This diagram shows the current associations, and it is indeed recursive.  I know you can have these types of associations, but I'm not sure how to set them up in Sequelize.

**Comment by dpkillian** [comment]
Alternatively, we could have:
Users -> have items --> items have tasks.
That might also work.  However, I tried to setup the models this way and still had errors.

**Comment by esharri2** [comment]
Items have one user. Tasks have one item. 

That's how it is in my head. I'm trying to think purely in terms of what data relationships we need in order to make our app do what it needs to do. Seems too simple though :)

**Comment by dpkillian** [comment]
I think this is correct.  But I wasn’t able to get that to work with the sequelize associations.

**Comment by esharri2** [comment]
Models should be good to go!
